# Generated by Django 4.0.5 on 2022-06-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('noOfCustomers', models.IntegerField()),
                ('turnOver', models.IntegerField()),
            ],
        ),
    ]
